version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    container_name: trading-bot-postgres
    environment:
      POSTGRES_DB: trading_bot
      POSTGRES_USER: trading
      POSTGRES_PASSWORD: trading
      POSTGRES_INITDB_ARGS: "-E UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trading -d trading_bot"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.10-alpine
    container_name: trading-bot-nats
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP management
    command: 
      - "--jetstream"
      - "--store_dir=/data"
      - "--max_file_store=10GB"
    volumes:
      - nats_data:/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  nats_data:
    driver: local

